#!/bin/bash

echo "Format All:"

root="$(git rev-parse --show-toplevel)"
[ -d "$root" ] || exit 1

owndir="$(cd "$(dirname "$0")"; pwd -P)"

OS_NAME=$(uname)

if [ "$OS_NAME" = "Darwin" ]; then
  FIND_ARGS="-perm +0111"
else
  FIND_ARGS="-executable"
fi

# We cannot store \0 in variables!
allFiles=$(git ls-tree -r HEAD --name-only | tr '\n' '\0' | base64 )

find "$owndir"/autoformat -type f $FIND_ARGS | {
  abort=0

  while read formatter ; do
    magic="$formatter".magic
    patterns="$formatter".patterns
    [ -f "$patterns" -o -f "$magic" ] || continue

    echo -ne "$allFiles" | base64 -D | {
      labort=0

      while IFS=; read -r -d $'\0' orig ; do
        orig="${root}/${orig}"
        # file matches one of the patterns
        match_pattern=''
        [ -f "$patterns" ] && echo "$orig" | grep -Eqif "$patterns" && match_pattern='1'

        # file’s libmagic output matches
        match_magic=''
        [ $match_pattern ] || {
          [ -f "$magic" ] && file "$orig" | grep -Eqif "$magic" && match_magic='1'
        }

        # if none, ignore
        [ "$match_pattern" -o "$match_magic" ] ||  continue

        "$formatter" "$orig" || labort=1
      done

      exit $labort
    } || abort=1
  done

  exit $abort
}

echo "Format All: [DONE]"