#!/bin/bash
root="$(git rev-parse --show-toplevel)"
[ -d "$root" ] || exit 1
preCommitFileChanged="${root}/.pre-commit-changed"

# check if file is here
[ -f "${preCommitFileChanged}" ] || exit 0

echo "Post-Commit Hook [START]: add automatically changed files ..."

function addFile()
{
    file="$1"
    echo "stage file: ${file}"
    git add ${file}
}
export -f addFile

cat "${preCommitFileChanged}" | xargs -n 1 -0 -I {} bash -c 'addFile "${@}"' _ {} || (deleteFile; echo "Error!"; exit 0)

# Delete the file
rm "${preCommitFileChanged}"

# Show the status
git status

# Allows us to read user input below, assigns stdin to keyboard
# exec < /dev/tty
# read -p "Post-Commit Hook: Do you want to auto amend-commit the changed files? (Y/n) (default: n) " yn
if [ "$yn" = "" ]; then
    yn='Y'
fi
case $yn in
    [Y] ) git commit --amend -C HEAD --no-verify
esac

echo "Post-Commit Hook [DONE]"


