#!/bin/bash

echo "Pre-Commit Hook: autoformat"

root="$(git rev-parse --show-toplevel)"
[ -d "$root" ] || exit 1

owndir="$(cd "$(dirname "$0")"; pwd -P)"

OS_NAME=$(uname)

allFiles=$(git diff --name-only --cached | tr '\n' '\0' | base64 )

function findExecutables(){
  find "$owndir/autoformat" -type f -perm +0111 > /dev/null 2>&1
  if [ $? -eq 0 ] ; then
    find "$owndir/autoformat" -type f -perm +0111
  else
    find "$owndir/autoformat" -type f -executable
  fi
}

findExecutables | {
  abort=0

  while read formatter ; do
    magic="$formatter".magic
    patterns="$formatter".patterns
    [ -f "$patterns" -o -f "$magic" ] || continue

    echo -ne "$allFiles" | base64 -D | {
      labort=0

      while IFS=; read -r -d $'\0' orig ; do
        orig="${root}/${orig}"
        #echo "$orig"
        # file is getting deleted, ignore
        [ -f "$orig" ] || continue

        # file matches one of the patterns
        match_pattern=''
        [ -f "$patterns" ] && echo "$orig" | grep -Eqif "$patterns" && match_pattern='1'

        # file’s libmagic output matches
        match_magic=''
        [ $match_pattern ] || {
          [ -f "$magic" ] && file "$orig" | grep -Eqif "$magic" && match_magic='1'
        }

        # if none, ignore
        [ "$match_pattern" -o "$match_magic" ] ||  continue

        "$formatter" "$orig" || labort=1
        git add "$orig"
      done

      exit $labort
    } || abort=1
  done

  exit $abort
}

echo "Pre-Commit Hook: autoformat [DONE]"