#!/bin/bash
# format all .cpp|.hpp files in the repository

set -e

REPO_DIR="$(git rev-parse --show-toplevel)"

cd "${REPO_DIR}"
echo "  -> formatting file: $1"
cmake-format -i -c "${REPO_DIR}/.cmake-format.yaml" "$1"