#!/bin/bash
# format all .cpp|.hpp files in the repository

set -e

REPO_DIR="$(git rev-parse --show-toplevel)"

function formatFile() {
    set -e
    file=$1
    echo "  -> formatting file: $file"
    clang-format -style="file" -assume-filename="" -fallback-style=none -i ${file} || { echo 'fatal: `clang-format` failed for:' "$file"; exit 1; }
}
export -f formatFile

function formatCpp() {
    find "$1" -regextype posix-extended  -regex "$REPO_DIR/(include|src|examples|tests|gui|benchmarks)/.*" -and -not -iname "*generated*" | xargs -I {} bash -c 'formatFile "${@}"' _ {}
}

cd "${REPO_DIR}"
formatCpp "$1"