#!/bin/bash
# format all TypeScript .ts files in the repository
# to use this tool install: npm install -g typescript-formatter

set -e

REPO_DIR="$(git rev-parse --show-toplevel)"

function formatFile() {
    file="$1"
    config="$2"
    echo "  -> formatting file: $file"
    prettier --config="${config}" --write "${file}" || { echo 'fatal: `prettier` failed for:' "$file" >&2 ; exit 1; }
}
export -f formatFile

function formatTS() {
    find "$1" -regextype posix-extended  \
              -regex "$REPO_DIR/(gui)/.*" \
              -and -not -iname "*generated*"  | \
              xargs -I {} bash -c 'formatFile "${@}"' _ {} "${REPO_DIR}/gui/executionGraphGui/client/.prettierrc"
}

formatTS "$1"
