// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DATATYPES_H_
#define FLATBUFFERS_GENERATED_DATATYPES_H_

#include "flatbuffers/flatbuffers.h"

#include "executionGraphGUI/messages/schemas/ConstructorKeyValue_generated.h"
#include "executionGraphGUI/messages/schemas/CycleDescription_generated.h"
#include "executionGraph/serialization/schemas/SocketLink_generated.h"

#endif  // FLATBUFFERS_GENERATED_DATATYPES_H_
