#!/bin/bash
# format all .cpp|.hpp files in the repository

REPO_DIR="$(git rev-parse --show-toplevel)"

newHeader="//! ========================================================================================\
\n//!  ExecutionGraph\
\n//!  Copyright (C) 2014 by Gabriel Nützi <gnuetzi (at) gmail (døt) com>\
\n//! \
\n//!  @date Mon Jan 08 2018\
\n//!  @author Gabriel Nützi, <gnuetzi (at) gmail (døt) com>\
\n//! \
\n//!  This Source Code Form is subject to the terms of the Mozilla Public\
\n//!  License, v. 2.0. If a copy of the MPL was not distributed with this\
\n//!  file, You can obtain one at http://mozilla.org/MPL/2.0/.\
\n//! ========================================================================================"

function formatFile() {
    file=$1
    echo "formatting file: $file"
    clang-format -style=file -i ${file} || echo 'fatal: `clang-format` failed for:' "$file" && exit 1
}
export -f formatFile

function formatCpp() {
    find "$1" -ipath "$2*" | xargs -I {} bash -c 'formatFile "${@}"' _ {}
}

formatCpp "$1" "$REPO_DIR/include"  
formatCpp "$1" "$REPO_DIR/src" 
formatCpp "$1" "$REPO_DIR/examples" 
formatCpp "$1" "$REPO_DIR/tests" 
formatCpp "$1" "$REPO_DIR/gui"
formatCpp "$1" "$REPO_DIR/benchmarks"