#!/bin/bash
# format all XML (HTML) files in the repository
# to use this tool install: npm install -g xmllint

REPO_DIR="$(git rev-parse --show-toplevel)"
owndir="$(cd "$(dirname "$0")"; pwd -P)"

function formatFile() {
    file=$1
    echo "formatting html file: $file"
    echo "file: $file" >> tidy.log
    tidy -config "$2" -m $file 2>>tidy.log #|| echo 'fatal: `tidy` failed for:' "$file" >&2 && exit 1
    # ignore tidy errors!
}
export -f formatFile

function formatHTML() {

    find "$1" \( -ipath "$2*" \) | xargs -I {} bash -c 'formatFile "${@}"' _ {} "$owndir/tidy.conf"
}

formatHTML "$1" "$REPO_DIR/gui"