#!/bin/sh
# format all XML (HTML) files in the repository
# to use this tool install: npm install -g xmllint

REPO_DIR="$(git rev-parse --show-toplevel)"
owndir="$(cd "$(dirname "$0")"; pwd -P)"

function formatFile() {
    file=$1
    echo "formatting html file: $file"
    tidy -config "$2" -m $file || echo 'fatal: `tidy` failed for:' "$file" >&2 && exit 1
}
export -f formatFile

function formatHTML() {

    find "$1" \( -ipath "$2*" \) | xargs -I {} bash -c 'formatFile "${@}"' _ {} "$owndir/tidy.conf"
}

formatHTML "$1" "$REPO_DIR/gui"