#!/bin/bash
# format all TypeScript .ts files in the repository
# to use this tool install: npm install -g typescript-formatter

REPO_DIR="$(git rev-parse --show-toplevel)"

function formatTS() {
    find "$1" \( -ipath "$2*" \)  | xargs tsfmt --replace --baseDir "$REPO_DIR"
}

formatTS "$1" "$REPO_DIR/gui"