#!/bin/bash
# format all TypeScript .ts files in the repository
# to use this tool install: npm install -g typescript-formatter

REPO_DIR="$(git rev-parse --show-toplevel)"

function formatFile() {
    file=$1
    echo "formatting file: $file"
    tsfmt --replace --baseDir "$REPO_DIR" "${file}" || echo 'fatal: `tsfmt` failed for:' "$file" >&2 && exit 1
}
export -f formatFile

function formatTS() {
    find "$1" -ipath "$2*" | xargs -I {} bash -c 'formatFile "${@}"' _ {}
}

formatTS "$1" "$REPO_DIR/gui"