// automatically generated by the FlatBuffers compiler, do not modify

import * as NS10534429299233269798 from "./NodeTypeDescription_generated";
import * as NS2542758913571862537 from "./SocketTypeDescription_generated";
/**
 * @constructor
 */
export namespace executionGraph.serialization{
export class GraphTypeDescription {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns GraphTypeDescription
 */
__init(i:number, bb:flatbuffers.ByteBuffer):GraphTypeDescription {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param GraphTypeDescription= obj
 * @returns GraphTypeDescription
 */
static getRootAsGraphTypeDescription(bb:flatbuffers.ByteBuffer, obj?:GraphTypeDescription):GraphTypeDescription {
  return (obj || new GraphTypeDescription).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param number index
 * @param executionGraph.serialization.SocketTypeDescription= obj
 * @returns executionGraph.serialization.SocketTypeDescription
 */
socketTypeDescriptions(index: number, obj?:NS2542758913571862537.executionGraph.serialization.SocketTypeDescription):NS2542758913571862537.executionGraph.serialization.SocketTypeDescription|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new NS2542758913571862537.executionGraph.serialization.SocketTypeDescription).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
};

/**
 * @returns number
 */
socketTypeDescriptionsLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param number index
 * @param executionGraph.serialization.NodeTypeDescription= obj
 * @returns executionGraph.serialization.NodeTypeDescription
 */
nodeTypeDescriptions(index: number, obj?:NS10534429299233269798.executionGraph.serialization.NodeTypeDescription):NS10534429299233269798.executionGraph.serialization.NodeTypeDescription|null {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new NS10534429299233269798.executionGraph.serialization.NodeTypeDescription).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
};

/**
 * @returns number
 */
nodeTypeDescriptionsLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
description():string|null
description(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
description(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static start(builder:flatbuffers.Builder) {
  builder.startObject(5);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset idOffset
 */
static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nameOffset
 */
static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset socketTypeDescriptionsOffset
 */
static addSocketTypeDescriptions(builder:flatbuffers.Builder, socketTypeDescriptionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, socketTypeDescriptionsOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createSocketTypeDescriptionsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startSocketTypeDescriptionsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nodeTypeDescriptionsOffset
 */
static addNodeTypeDescriptions(builder:flatbuffers.Builder, nodeTypeDescriptionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, nodeTypeDescriptionsOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createNodeTypeDescriptionsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startNodeTypeDescriptionsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset descriptionOffset
 */
static addDescription(builder:flatbuffers.Builder, descriptionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, descriptionOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static end(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // id
  builder.requiredField(offset, 6); // name
  builder.requiredField(offset, 8); // socketTypeDescriptions
  builder.requiredField(offset, 12); // description
  return offset;
};

static create(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, nameOffset:flatbuffers.Offset, socketTypeDescriptionsOffset:flatbuffers.Offset, nodeTypeDescriptionsOffset:flatbuffers.Offset, descriptionOffset:flatbuffers.Offset):flatbuffers.Offset {
  GraphTypeDescription.start(builder);
  GraphTypeDescription.addId(builder, idOffset);
  GraphTypeDescription.addName(builder, nameOffset);
  GraphTypeDescription.addSocketTypeDescriptions(builder, socketTypeDescriptionsOffset);
  GraphTypeDescription.addNodeTypeDescriptions(builder, nodeTypeDescriptionsOffset);
  GraphTypeDescription.addDescription(builder, descriptionOffset);
  return GraphTypeDescription.end(builder);
}
}
}
