// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GRAPHINFOMESSAGES_EXECUTIONGRAPHGUI_SERIALIZATION_H_
#define FLATBUFFERS_GENERATED_GRAPHINFOMESSAGES_EXECUTIONGRAPHGUI_SERIALIZATION_H_

#include "flatbuffers/flatbuffers.h"

namespace executionGraphGUI {
namespace serialization {

struct NodeTypeDescription;

struct SocketTypeDescription;

struct GetAllGraphTypeDescriptionsResponse;

struct NodeTypeDescription FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_NAME = 4,
    VT_TYPE = 6
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::String *type() const {
    return GetPointer<const flatbuffers::String *>(VT_TYPE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.Verify(name()) &&
           VerifyOffset(verifier, VT_TYPE) &&
           verifier.Verify(type()) &&
           verifier.EndTable();
  }
};

struct NodeTypeDescriptionBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(NodeTypeDescription::VT_NAME, name);
  }
  void add_type(flatbuffers::Offset<flatbuffers::String> type) {
    fbb_.AddOffset(NodeTypeDescription::VT_TYPE, type);
  }
  explicit NodeTypeDescriptionBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  NodeTypeDescriptionBuilder &operator=(const NodeTypeDescriptionBuilder &);
  flatbuffers::Offset<NodeTypeDescription> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<NodeTypeDescription>(end);
    return o;
  }
};

inline flatbuffers::Offset<NodeTypeDescription> CreateNodeTypeDescription(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::String> type = 0) {
  NodeTypeDescriptionBuilder builder_(_fbb);
  builder_.add_type(type);
  builder_.add_name(name);
  return builder_.Finish();
}

inline flatbuffers::Offset<NodeTypeDescription> CreateNodeTypeDescriptionDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const char *type = nullptr) {
  return executionGraphGUI::serialization::CreateNodeTypeDescription(
      _fbb,
      name ? _fbb.CreateString(name) : 0,
      type ? _fbb.CreateString(type) : 0);
}

struct SocketTypeDescription FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_NAME = 4,
    VT_TYPE = 6
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::String *type() const {
    return GetPointer<const flatbuffers::String *>(VT_TYPE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.Verify(name()) &&
           VerifyOffset(verifier, VT_TYPE) &&
           verifier.Verify(type()) &&
           verifier.EndTable();
  }
};

struct SocketTypeDescriptionBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(SocketTypeDescription::VT_NAME, name);
  }
  void add_type(flatbuffers::Offset<flatbuffers::String> type) {
    fbb_.AddOffset(SocketTypeDescription::VT_TYPE, type);
  }
  explicit SocketTypeDescriptionBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  SocketTypeDescriptionBuilder &operator=(const SocketTypeDescriptionBuilder &);
  flatbuffers::Offset<SocketTypeDescription> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SocketTypeDescription>(end);
    return o;
  }
};

inline flatbuffers::Offset<SocketTypeDescription> CreateSocketTypeDescription(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::String> type = 0) {
  SocketTypeDescriptionBuilder builder_(_fbb);
  builder_.add_type(type);
  builder_.add_name(name);
  return builder_.Finish();
}

inline flatbuffers::Offset<SocketTypeDescription> CreateSocketTypeDescriptionDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const char *type = nullptr) {
  return executionGraphGUI::serialization::CreateSocketTypeDescription(
      _fbb,
      name ? _fbb.CreateString(name) : 0,
      type ? _fbb.CreateString(type) : 0);
}

struct GetAllGraphTypeDescriptionsResponse FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ID = 4,
    VT_NODETYPEDESCRIPTIONS = 6,
    VT_SOCKETTYPEDESCRIPTIONS = 8
  };
  const flatbuffers::String *id() const {
    return GetPointer<const flatbuffers::String *>(VT_ID);
  }
  const flatbuffers::Vector<flatbuffers::Offset<NodeTypeDescription>> *nodeTypeDescriptions() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<NodeTypeDescription>> *>(VT_NODETYPEDESCRIPTIONS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<SocketTypeDescription>> *socketTypeDescriptions() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<SocketTypeDescription>> *>(VT_SOCKETTYPEDESCRIPTIONS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.Verify(id()) &&
           VerifyOffset(verifier, VT_NODETYPEDESCRIPTIONS) &&
           verifier.Verify(nodeTypeDescriptions()) &&
           verifier.VerifyVectorOfTables(nodeTypeDescriptions()) &&
           VerifyOffset(verifier, VT_SOCKETTYPEDESCRIPTIONS) &&
           verifier.Verify(socketTypeDescriptions()) &&
           verifier.VerifyVectorOfTables(socketTypeDescriptions()) &&
           verifier.EndTable();
  }
};

struct GetAllGraphTypeDescriptionsResponseBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(flatbuffers::Offset<flatbuffers::String> id) {
    fbb_.AddOffset(GetAllGraphTypeDescriptionsResponse::VT_ID, id);
  }
  void add_nodeTypeDescriptions(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<NodeTypeDescription>>> nodeTypeDescriptions) {
    fbb_.AddOffset(GetAllGraphTypeDescriptionsResponse::VT_NODETYPEDESCRIPTIONS, nodeTypeDescriptions);
  }
  void add_socketTypeDescriptions(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<SocketTypeDescription>>> socketTypeDescriptions) {
    fbb_.AddOffset(GetAllGraphTypeDescriptionsResponse::VT_SOCKETTYPEDESCRIPTIONS, socketTypeDescriptions);
  }
  explicit GetAllGraphTypeDescriptionsResponseBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  GetAllGraphTypeDescriptionsResponseBuilder &operator=(const GetAllGraphTypeDescriptionsResponseBuilder &);
  flatbuffers::Offset<GetAllGraphTypeDescriptionsResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<GetAllGraphTypeDescriptionsResponse>(end);
    return o;
  }
};

inline flatbuffers::Offset<GetAllGraphTypeDescriptionsResponse> CreateGetAllGraphTypeDescriptionsResponse(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> id = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<NodeTypeDescription>>> nodeTypeDescriptions = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<SocketTypeDescription>>> socketTypeDescriptions = 0) {
  GetAllGraphTypeDescriptionsResponseBuilder builder_(_fbb);
  builder_.add_socketTypeDescriptions(socketTypeDescriptions);
  builder_.add_nodeTypeDescriptions(nodeTypeDescriptions);
  builder_.add_id(id);
  return builder_.Finish();
}

inline flatbuffers::Offset<GetAllGraphTypeDescriptionsResponse> CreateGetAllGraphTypeDescriptionsResponseDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const std::vector<flatbuffers::Offset<NodeTypeDescription>> *nodeTypeDescriptions = nullptr,
    const std::vector<flatbuffers::Offset<SocketTypeDescription>> *socketTypeDescriptions = nullptr) {
  return executionGraphGUI::serialization::CreateGetAllGraphTypeDescriptionsResponse(
      _fbb,
      id ? _fbb.CreateString(id) : 0,
      nodeTypeDescriptions ? _fbb.CreateVector<flatbuffers::Offset<NodeTypeDescription>>(*nodeTypeDescriptions) : 0,
      socketTypeDescriptions ? _fbb.CreateVector<flatbuffers::Offset<SocketTypeDescription>>(*socketTypeDescriptions) : 0);
}

}  // namespace serialization
}  // namespace executionGraphGUI

#endif  // FLATBUFFERS_GENERATED_GRAPHINFOMESSAGES_EXECUTIONGRAPHGUI_SERIALIZATION_H_
