// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GRAPHTYPEDESCRIPTION_EXECUTIONGRAPHGUI_SERIALIZATION_H_
#define FLATBUFFERS_GENERATED_GRAPHTYPEDESCRIPTION_EXECUTIONGRAPHGUI_SERIALIZATION_H_

#include "flatbuffers/flatbuffers.h"

#include "NodeTypeDescription_generated.h"
#include "SocketTypeDescription_generated.h"

namespace executionGraphGUI {
namespace serialization {

struct GraphTypeDescription;

struct GraphTypeDescription FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_NAME = 4,
    VT_ID = 6,
    VT_NODETYPEDESCRIPTIONS = 8,
    VT_SOCKETTYPEDESCRIPTIONS = 10
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::String *id() const {
    return GetPointer<const flatbuffers::String *>(VT_ID);
  }
  const flatbuffers::Vector<flatbuffers::Offset<NodeTypeDescription>> *nodeTypeDescriptions() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<NodeTypeDescription>> *>(VT_NODETYPEDESCRIPTIONS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<SocketTypeDescription>> *socketTypeDescriptions() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<SocketTypeDescription>> *>(VT_SOCKETTYPEDESCRIPTIONS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NAME) &&
           verifier.Verify(name()) &&
           VerifyOffsetRequired(verifier, VT_ID) &&
           verifier.Verify(id()) &&
           VerifyOffset(verifier, VT_NODETYPEDESCRIPTIONS) &&
           verifier.Verify(nodeTypeDescriptions()) &&
           verifier.VerifyVectorOfTables(nodeTypeDescriptions()) &&
           VerifyOffset(verifier, VT_SOCKETTYPEDESCRIPTIONS) &&
           verifier.Verify(socketTypeDescriptions()) &&
           verifier.VerifyVectorOfTables(socketTypeDescriptions()) &&
           verifier.EndTable();
  }
};

struct GraphTypeDescriptionBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(GraphTypeDescription::VT_NAME, name);
  }
  void add_id(flatbuffers::Offset<flatbuffers::String> id) {
    fbb_.AddOffset(GraphTypeDescription::VT_ID, id);
  }
  void add_nodeTypeDescriptions(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<NodeTypeDescription>>> nodeTypeDescriptions) {
    fbb_.AddOffset(GraphTypeDescription::VT_NODETYPEDESCRIPTIONS, nodeTypeDescriptions);
  }
  void add_socketTypeDescriptions(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<SocketTypeDescription>>> socketTypeDescriptions) {
    fbb_.AddOffset(GraphTypeDescription::VT_SOCKETTYPEDESCRIPTIONS, socketTypeDescriptions);
  }
  explicit GraphTypeDescriptionBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  GraphTypeDescriptionBuilder &operator=(const GraphTypeDescriptionBuilder &);
  flatbuffers::Offset<GraphTypeDescription> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<GraphTypeDescription>(end);
    fbb_.Required(o, GraphTypeDescription::VT_NAME);
    fbb_.Required(o, GraphTypeDescription::VT_ID);
    return o;
  }
};

inline flatbuffers::Offset<GraphTypeDescription> CreateGraphTypeDescription(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::String> id = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<NodeTypeDescription>>> nodeTypeDescriptions = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<SocketTypeDescription>>> socketTypeDescriptions = 0) {
  GraphTypeDescriptionBuilder builder_(_fbb);
  builder_.add_socketTypeDescriptions(socketTypeDescriptions);
  builder_.add_nodeTypeDescriptions(nodeTypeDescriptions);
  builder_.add_id(id);
  builder_.add_name(name);
  return builder_.Finish();
}

inline flatbuffers::Offset<GraphTypeDescription> CreateGraphTypeDescriptionDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const char *id = nullptr,
    const std::vector<flatbuffers::Offset<NodeTypeDescription>> *nodeTypeDescriptions = nullptr,
    const std::vector<flatbuffers::Offset<SocketTypeDescription>> *socketTypeDescriptions = nullptr) {
  return executionGraphGUI::serialization::CreateGraphTypeDescription(
      _fbb,
      name ? _fbb.CreateString(name) : 0,
      id ? _fbb.CreateString(id) : 0,
      nodeTypeDescriptions ? _fbb.CreateVector<flatbuffers::Offset<NodeTypeDescription>>(*nodeTypeDescriptions) : 0,
      socketTypeDescriptions ? _fbb.CreateVector<flatbuffers::Offset<SocketTypeDescription>>(*socketTypeDescriptions) : 0);
}

}  // namespace serialization
}  // namespace executionGraphGUI

#endif  // FLATBUFFERS_GENERATED_GRAPHTYPEDESCRIPTION_EXECUTIONGRAPHGUI_SERIALIZATION_H_
