
@startuml core
set namespaceSeparator ::
skinparam shadowing false
skinparam defaultFontName "Fira Code"

skinparam class{
    BorderColor<< Connections >> Blue
    BorderThickness<< Connections >> 3

    BorderColor<< Node >> Green
    BorderThickness<< Node >> 3
}

class DummyNode{
    --  In/Out Declerations --
    + inDecls
    + outDecls
    --
    + socket<decl>()
    + dataHandle<decl>()
    -- Sockets --
    - m_inSockets
    - m_outSockets
}

namespace executionGraph{

    class LogicNode <<Node>> {
        + id()
        --
        + virtual init() = 0
        + virtual reset() = 0
        + virtual compute() = 0
        --
        + registerInputs(...)
        + registerOutputs(...)
        --
        - m_inputs
        - m_outputs
    }

    class LogicSocketInput<Data> {
        + dataHandle() [const]
        --
        + connect<SocketData>(SocketData&)
        + disconnect() override
        + connections() [const]
        --
        - Connections m_connections
    }

    class LogicSocketOutput<Data> {
        + dataHandle() [const]
        --
        + connect<SocketData>(SocketData&)
        + disconnect() override
        + connections() [const]
        --
        - Connections m_connections
    }

    class LogicSocketBase<IsInput> {
        + type()
        + index()
        + parent()
        + castToType<T>()
        --
        + connect<Socket>(Socket&)
        + virtual disconnect() = 0
    }

    class LogicSocketConnections<Traits, ParentSocket> << Connections >>{
        Connection for input/output sockets
        --
        + connect(SocketData&)
        + disconnect(SocketData&)
        --
        - SocketDataConnections* m_connections
        - Parent* m_parent
    }

    namespace userData{
        class LogicSocketDataConnections<Traits, ParentSocket> << Connections >> {
            Connection for data sockets
            --
            + connect(InSocket&)
            + disconnect(InSocket&)
            + connect(OutSocket&)
            + disconnect(OutSocket&)
            --
            - m_inputs
            - m_outputs
        }

        class LogicSocketData<Data>{
            + dataHandle() [const]
            + dataHandleConst()
            --
            + virtual connect(InSocketBase&) override
            + virtual disconnect(InSocketBase&) override
            + virtual connect(OutSocketBase&) override
            + virtual disconnect(OutSocketBase&) override
            + connections() [const]
            --
            - Data m_data
            - Connections m_connections
        }


        class LogicSocketDataRef<Args...>{
            + setReference(socketData)
            --
            - LogicSocketData<Args>* m_socketData
        }

    }

    class LogicSocketDataBase{
        + virtual connect(InSocketBase&) = 0
        + virtual disconnect(InSocketBase&) = 0
        + virtual connect(OutSocketBase&) = 0
        + virtual disconnect(OutSocketBase&) = 0
        --
        + type()
        + id()
    }
}

DummyNode -up-|> executionGraph::LogicNode

executionGraph::LogicSocketInput -up-|> executionGraph::LogicSocketBase
executionGraph::LogicSocketOutput -up-|> executionGraph::LogicSocketBase

executionGraph::LogicNode "*" o-up- executionGraph::LogicSocketBase 

' executionGraph::LogicSocketBase -[hidden]-> executionGraph::userData::LogicSocketData
' executionGraph::LogicSocketBase -up[hidden]-> executionGraph::userData::LogicSocketData


DummyNode "*" *-up- executionGraph::LogicSocketInput
DummyNode "*" *-up- executionGraph::LogicSocketOutput

executionGraph::LogicSocketInput "1" *-- executionGraph::LogicSocketConnections
executionGraph::LogicSocketOutput "1" *-- executionGraph::LogicSocketConnections

executionGraph::LogicSocketBase "1" o-down- executionGraph::LogicNode

executionGraph::userData::LogicSocketData -up-|> executionGraph::LogicSocketDataBase
executionGraph::userData::LogicSocketDataConnections "*" o-down- executionGraph::LogicSocketBase
executionGraph::userData::LogicSocketData -right-o "1" executionGraph::userData::LogicSocketDataRef
executionGraph::userData::LogicSocketData "1" *-down- executionGraph::userData::LogicSocketDataConnections

executionGraph::LogicSocketConnections "1" *-- executionGraph::userData::LogicSocketDataConnections : design-error

@enduml