
@startuml core
set namespaceSeparator ::
skinparam shadowing false
skinparam defaultFontName "Fira Code"

class DummyNode{
    --  In/Out Declerations --
    + inDecls
    + outDecls
    -- Sockets --
    - m_inSockets
    - m_outSockets
}

namespace executionGraph{

    class LogicNode{
        + init()
        + reset()
        + compute()

        + registerInputs(...)
        + registerOutputs(...)
        --
        - m_inputs
        - m_outputs
    }

    class LogicSocketInput<Data> {
        + dataHandle() [const]

        + connections() [const]
        --
        - Connections m_connections
    }

    class LogicSocketOutput<Data> {
        + dataHandle() [const]

        + connections() [const]
        --
        - Connections m_connections
    }

    class LogicSocketBase {
        + type()
        + index()
        + parent()
    }

    class LogicSocketInputBase {
        + castToType<T>() -> LogicSocketInput<T>
    }

    class LogicSocketOutputBase {
        + castToType<T>() -> LogicSocketOutput<T>
    }

    class LogicSocketConnections<Traits, ParentSocket>{
        Connection for input/output sockets
        --
        + connect(socketData)
        + disconnect(socketData)
        --
        SocketDataConnections* m_connections
        Parent* m_parent
    }

    namespace userData{
        class LogicSocketDataConnections<Traits, ParentSocket>{
            Connection for data sockets
            --
            + connect(socket)
            + disconnect(socket)
            --
            m_inputs
            m_outputs
        }

        class LogicSocketData<Data>{
            + dataHandle() [const]
            + dataHandleConst()

            + connections() [const]
            --
            - Data m_data
            - Connections m_connections
        }


        class LogicSocketDataRef<Args...>{
            + setReference(socketData)
            --
            - LogicSocketData<Args>* m_socketData
        }

    }

    class LogicSocketDataBase{

    }
}

DummyNode -up-|> executionGraph::LogicNode

executionGraph::LogicSocketInput -up-|> executionGraph::LogicSocketInputBase
executionGraph::LogicSocketOutput -up-|> executionGraph::LogicSocketOutputBase

executionGraph::LogicSocketInputBase -up-|> executionGraph::LogicSocketBase
executionGraph::LogicSocketOutputBase -up-|> executionGraph::LogicSocketBase
executionGraph::LogicSocketBase -[hidden]-> executionGraph::userData::LogicSocketData
executionGraph::LogicSocketBase -up[hidden]-> executionGraph::userData::LogicSocketData


DummyNode "*" *-up- executionGraph::LogicSocketInput
DummyNode "*" *-up- executionGraph::LogicSocketOutput

executionGraph::LogicSocketInput "1" *-- executionGraph::LogicSocketConnections
executionGraph::LogicSocketOutput "1" *-- executionGraph::LogicSocketConnections

executionGraph::LogicSocketBase "1" o-down- executionGraph::LogicNode

executionGraph::userData::LogicSocketData -up-|> executionGraph::LogicSocketDataBase
executionGraph::userData::LogicSocketDataConnections "*" o-down- executionGraph::LogicSocketInputBase
executionGraph::userData::LogicSocketDataConnections "*" o-down- executionGraph::LogicSocketOutputBase
executionGraph::userData::LogicSocketData -right-o "1" executionGraph::userData::LogicSocketDataRef
executionGraph::userData::LogicSocketData "1" *-down- executionGraph::userData::LogicSocketDataConnections

executionGraph::LogicSocketConnections "1" *-- executionGraph::userData::LogicSocketDataConnections : design-error

@enduml