// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var executionGraphGui = executionGraphGui || {};

/**
 * @const
 * @namespace
 */
executionGraphGui.serialization = executionGraphGui.serialization || {};

/**
 * @enum
 */
executionGraphGui.serialization.ConstructorValue = {
  NONE: 0, 0: 'NONE',
  Bool: 1, 1: 'Bool'
};

/**
 * @constructor
 */
executionGraphGui.serialization.Bool = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {executionGraphGui.serialization.Bool}
 */
executionGraphGui.serialization.Bool.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {boolean}
 */
executionGraphGui.serialization.Bool.prototype.value = function() {
  return !!this.bb.readInt8(this.bb_pos);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} value
 * @returns {flatbuffers.Offset}
 */
executionGraphGui.serialization.Bool.create = function(builder, value) {
  builder.prep(1, 1);
  builder.writeInt8(+value);
  return builder.offset();
};

/**
 * @constructor
 */
executionGraphGui.serialization.ConstructorKV = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {executionGraphGui.serialization.ConstructorKV}
 */
executionGraphGui.serialization.ConstructorKV.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {executionGraphGui.serialization.ConstructorKV=} obj
 * @returns {executionGraphGui.serialization.ConstructorKV}
 */
executionGraphGui.serialization.ConstructorKV.getRootAsConstructorKV = function(bb, obj) {
  return (obj || new executionGraphGui.serialization.ConstructorKV).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
executionGraphGui.serialization.ConstructorKV.prototype.key = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {number} index
 * @returns {executionGraphGui.serialization.ConstructorValue}
 */
executionGraphGui.serialization.ConstructorKV.prototype.valueType = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {executionGraphGui.serialization.ConstructorValue} */ (this.bb.readUint8(this.bb.__vector(this.bb_pos + offset) + index)) : /** @type {executionGraphGui.serialization.ConstructorValue} */ (0);
};

/**
 * @returns {number}
 */
executionGraphGui.serialization.ConstructorKV.prototype.valueTypeLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Uint8Array}
 */
executionGraphGui.serialization.ConstructorKV.prototype.valueTypeArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {number} index
 * @param {flatbuffers.Table=} obj
 * @returns {?flatbuffers.Table}
 */
executionGraphGui.serialization.ConstructorKV.prototype.value = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__union(obj, this.bb.__vector(this.bb_pos + offset) + index * 4) : null;
};

/**
 * @returns {number}
 */
executionGraphGui.serialization.ConstructorKV.prototype.valueLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
executionGraphGui.serialization.ConstructorKV.start = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} keyOffset
 */
executionGraphGui.serialization.ConstructorKV.addKey = function(builder, keyOffset) {
  builder.addFieldOffset(0, keyOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} valueTypeOffset
 */
executionGraphGui.serialization.ConstructorKV.addValueType = function(builder, valueTypeOffset) {
  builder.addFieldOffset(1, valueTypeOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<executionGraphGui.serialization.ConstructorValue>} data
 * @returns {flatbuffers.Offset}
 */
executionGraphGui.serialization.ConstructorKV.createValueTypeVector = function(builder, data) {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
executionGraphGui.serialization.ConstructorKV.startValueTypeVector = function(builder, numElems) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} valueOffset
 */
executionGraphGui.serialization.ConstructorKV.addValue = function(builder, valueOffset) {
  builder.addFieldOffset(2, valueOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
executionGraphGui.serialization.ConstructorKV.createValueVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
executionGraphGui.serialization.ConstructorKV.startValueVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
executionGraphGui.serialization.ConstructorKV.end = function(builder) {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // key
  builder.requiredField(offset, 6); // value_type
  builder.requiredField(offset, 8); // value
  return offset;
};

// Exports for Node.js and RequireJS
this.executionGraphGui = executionGraphGui;
