// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var executionGraph = executionGraph || {};

/**
 * @const
 * @namespace
 */
executionGraph.serialization = executionGraph.serialization || {};

/**
 * @const
 * @namespace
 */
var executionGraphGui = executionGraphGui || {};

/**
 * @const
 * @namespace
 */
executionGraphGui.serialization = executionGraphGui.serialization || {};

// Exports for Node.js and RequireJS
this.executionGraph = executionGraph;
this.executionGraphGui = executionGraphGui;
