// automatically generated by the FlatBuffers compiler, do not modify

import * as NS17842650861260698748 from "./CycleDescription_generated";
import * as NS6430394118259426465 from "@eg/serialization/SocketLinkDescription_generated";
import * as NS8768211991854589814 from "@eg/serialization/LogicNode_generated";
import * as NS489124886658682630 from "./ConstructorKeyValue_generated";
/**
 * @constructor
 */
export namespace executionGraphGui.serialization{
export class NodeConstructionInfo {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns NodeConstructionInfo
 */
__init(i:number, bb:flatbuffers.ByteBuffer):NodeConstructionInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param NodeConstructionInfo= obj
 * @returns NodeConstructionInfo
 */
static getRootAsNodeConstructionInfo(bb:flatbuffers.ByteBuffer, obj?:NodeConstructionInfo):NodeConstructionInfo {
  return (obj || new NodeConstructionInfo).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
type():string|null
type(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
type(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param number index
 * @param executionGraphGui.serialization.ConstructorKV= obj
 * @returns executionGraphGui.serialization.ConstructorKV
 */
constructorArgs(index: number, obj?:NS489124886658682630.executionGraphGui.serialization.ConstructorKV):NS489124886658682630.executionGraphGui.serialization.ConstructorKV|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new NS489124886658682630.executionGraphGui.serialization.ConstructorKV).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
};

/**
 * @returns number
 */
constructorArgsLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startNodeConstructionInfo(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset typeOffset
 */
static addType(builder:flatbuffers.Builder, typeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, typeOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nameOffset
 */
static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset constructorArgsOffset
 */
static addConstructorArgs(builder:flatbuffers.Builder, constructorArgsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, constructorArgsOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createConstructorArgsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startConstructorArgsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endNodeConstructionInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // type
  builder.requiredField(offset, 6); // name
  return offset;
};

}
}
/**
 * @constructor
 */
export namespace executionGraphGui.serialization{
export class AddNodeRequest {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns AddNodeRequest
 */
__init(i:number, bb:flatbuffers.ByteBuffer):AddNodeRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param AddNodeRequest= obj
 * @returns AddNodeRequest
 */
static getRootAsAddNodeRequest(bb:flatbuffers.ByteBuffer, obj?:AddNodeRequest):AddNodeRequest {
  return (obj || new AddNodeRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
graphId():string|null
graphId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
graphId(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param executionGraphGui.serialization.NodeConstructionInfo= obj
 * @returns executionGraphGui.serialization.NodeConstructionInfo|null
 */
node(obj?:executionGraphGui.serialization.NodeConstructionInfo):executionGraphGui.serialization.NodeConstructionInfo|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new executionGraphGui.serialization.NodeConstructionInfo).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startAddNodeRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset graphIdOffset
 */
static addGraphId(builder:flatbuffers.Builder, graphIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, graphIdOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nodeOffset
 */
static addNode(builder:flatbuffers.Builder, nodeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nodeOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endAddNodeRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // graphId
  builder.requiredField(offset, 6); // node
  return offset;
};

}
}
/**
 * @constructor
 */
export namespace executionGraphGui.serialization{
export class AddNodeResponse {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns AddNodeResponse
 */
__init(i:number, bb:flatbuffers.ByteBuffer):AddNodeResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param AddNodeResponse= obj
 * @returns AddNodeResponse
 */
static getRootAsAddNodeResponse(bb:flatbuffers.ByteBuffer, obj?:AddNodeResponse):AddNodeResponse {
  return (obj || new AddNodeResponse).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param executionGraph.serialization.LogicNode= obj
 * @returns executionGraph.serialization.LogicNode|null
 */
node(obj?:NS8768211991854589814.executionGraph.serialization.LogicNode):NS8768211991854589814.executionGraph.serialization.LogicNode|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new NS8768211991854589814.executionGraph.serialization.LogicNode).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startAddNodeResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nodeOffset
 */
static addNode(builder:flatbuffers.Builder, nodeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nodeOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endAddNodeResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // node
  return offset;
};

}
}
/**
 * @constructor
 */
export namespace executionGraphGui.serialization{
export class RemoveNodeRequest {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns RemoveNodeRequest
 */
__init(i:number, bb:flatbuffers.ByteBuffer):RemoveNodeRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param RemoveNodeRequest= obj
 * @returns RemoveNodeRequest
 */
static getRootAsRemoveNodeRequest(bb:flatbuffers.ByteBuffer, obj?:RemoveNodeRequest):RemoveNodeRequest {
  return (obj || new RemoveNodeRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
graphId():string|null
graphId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
graphId(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns flatbuffers.Long
 */
nodeId():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @param flatbuffers.Builder builder
 */
static startRemoveNodeRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset graphIdOffset
 */
static addGraphId(builder:flatbuffers.Builder, graphIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, graphIdOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Long nodeId
 */
static addNodeId(builder:flatbuffers.Builder, nodeId:flatbuffers.Long) {
  builder.addFieldInt64(1, nodeId, builder.createLong(0, 0));
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endRemoveNodeRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // graphId
  return offset;
};

}
}
/**
 * @constructor
 */
export namespace executionGraphGui.serialization{
export class AddConnectionRequest {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns AddConnectionRequest
 */
__init(i:number, bb:flatbuffers.ByteBuffer):AddConnectionRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param AddConnectionRequest= obj
 * @returns AddConnectionRequest
 */
static getRootAsAddConnectionRequest(bb:flatbuffers.ByteBuffer, obj?:AddConnectionRequest):AddConnectionRequest {
  return (obj || new AddConnectionRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
graphId():string|null
graphId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
graphId(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param executionGraph.serialization.SocketLinkDescription= obj
 * @returns executionGraph.serialization.SocketLinkDescription|null
 */
socketLink(obj?:NS6430394118259426465.executionGraph.serialization.SocketLinkDescription):NS6430394118259426465.executionGraph.serialization.SocketLinkDescription|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new NS6430394118259426465.executionGraph.serialization.SocketLinkDescription).__init(this.bb_pos + offset, this.bb!) : null;
};

/**
 * @returns boolean
 */
checkForCycles():boolean {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param flatbuffers.Builder builder
 */
static startAddConnectionRequest(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset graphIdOffset
 */
static addGraphId(builder:flatbuffers.Builder, graphIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, graphIdOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset socketLinkOffset
 */
static addSocketLink(builder:flatbuffers.Builder, socketLinkOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, socketLinkOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param boolean checkForCycles
 */
static addCheckForCycles(builder:flatbuffers.Builder, checkForCycles:boolean) {
  builder.addFieldInt8(2, +checkForCycles, +false);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endAddConnectionRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // graphId
  builder.requiredField(offset, 6); // socketLink
  return offset;
};

}
}
/**
 * @constructor
 */
export namespace executionGraphGui.serialization{
export class AddConnectionResponse {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns AddConnectionResponse
 */
__init(i:number, bb:flatbuffers.ByteBuffer):AddConnectionResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param AddConnectionResponse= obj
 * @returns AddConnectionResponse
 */
static getRootAsAddConnectionResponse(bb:flatbuffers.ByteBuffer, obj?:AddConnectionResponse):AddConnectionResponse {
  return (obj || new AddConnectionResponse).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param number index
 * @param executionGraphGui.serialization.CycleDescription= obj
 * @returns executionGraphGui.serialization.CycleDescription
 */
cycles(index: number, obj?:NS17842650861260698748.executionGraphGui.serialization.CycleDescription):NS17842650861260698748.executionGraphGui.serialization.CycleDescription|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new NS17842650861260698748.executionGraphGui.serialization.CycleDescription).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
};

/**
 * @returns number
 */
cyclesLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startAddConnectionResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset cyclesOffset
 */
static addCycles(builder:flatbuffers.Builder, cyclesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, cyclesOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createCyclesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startCyclesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endAddConnectionResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

}
}
/**
 * @constructor
 */
export namespace executionGraphGui.serialization{
export class RemoveConnectionRequest {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns RemoveConnectionRequest
 */
__init(i:number, bb:flatbuffers.ByteBuffer):RemoveConnectionRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param RemoveConnectionRequest= obj
 * @returns RemoveConnectionRequest
 */
static getRootAsRemoveConnectionRequest(bb:flatbuffers.ByteBuffer, obj?:RemoveConnectionRequest):RemoveConnectionRequest {
  return (obj || new RemoveConnectionRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
graphId():string|null
graphId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
graphId(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param executionGraph.serialization.SocketLinkDescription= obj
 * @returns executionGraph.serialization.SocketLinkDescription|null
 */
socketLink(obj?:NS6430394118259426465.executionGraph.serialization.SocketLinkDescription):NS6430394118259426465.executionGraph.serialization.SocketLinkDescription|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new NS6430394118259426465.executionGraph.serialization.SocketLinkDescription).__init(this.bb_pos + offset, this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startRemoveConnectionRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset graphIdOffset
 */
static addGraphId(builder:flatbuffers.Builder, graphIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, graphIdOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset socketLinkOffset
 */
static addSocketLink(builder:flatbuffers.Builder, socketLinkOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, socketLinkOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endRemoveConnectionRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // graphId
  builder.requiredField(offset, 6); // socketLink
  return offset;
};

}
}
