// automatically generated by the FlatBuffers compiler, do not modify

import * as NS11220090238097262337 from "@eg/serialization/SocketLinkDescription_generated";
import * as NS13873119913449574917 from "@eg/serialization/DataTypes_generated";
/**
 * @constructor
 */
export namespace executionGraph.serialization{
export class WorkspaceVisualization {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns WorkspaceVisualization
 */
__init(i:number, bb:flatbuffers.ByteBuffer):WorkspaceVisualization {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param WorkspaceVisualization= obj
 * @returns WorkspaceVisualization
 */
static getRoot(bb:flatbuffers.ByteBuffer, obj?:WorkspaceVisualization):WorkspaceVisualization {
  return (obj || new WorkspaceVisualization).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns flatbuffers.Long
 */
workspaceId():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @param Box2f= obj
 * @returns Box2f|null
 */
box(obj?:NS13873119913449574917.Box2f):NS13873119913449574917.Box2f|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new NS13873119913449574917.Box2f).__init(this.bb_pos + offset, this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static start(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Long workspaceId
 */
static addWorkspaceId(builder:flatbuffers.Builder, workspaceId:flatbuffers.Long) {
  builder.addFieldInt64(0, workspaceId, builder.createLong(0, 0));
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset boxOffset
 */
static addBox(builder:flatbuffers.Builder, boxOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, boxOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static end(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  builder.requiredField(offset, 6); // box
  return offset;
};

static create(builder:flatbuffers.Builder, workspaceId:flatbuffers.Long, boxOffset:flatbuffers.Offset):flatbuffers.Offset {
  WorkspaceVisualization.start(builder);
  WorkspaceVisualization.addWorkspaceId(builder, workspaceId);
  WorkspaceVisualization.addBox(builder, boxOffset);
  return WorkspaceVisualization.end(builder);
}
}
}
/**
 * @constructor
 */
export namespace executionGraph.serialization{
export class NodeVisualization {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns NodeVisualization
 */
__init(i:number, bb:flatbuffers.ByteBuffer):NodeVisualization {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param NodeVisualization= obj
 * @returns NodeVisualization
 */
static getRoot(bb:flatbuffers.ByteBuffer, obj?:NodeVisualization):NodeVisualization {
  return (obj || new NodeVisualization).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns flatbuffers.Long
 */
id():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param Vector2d= obj
 * @returns Vector2d|null
 */
position(obj?:NS13873119913449574917.Vector2d):NS13873119913449574917.Vector2d|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new NS13873119913449574917.Vector2d).__init(this.bb_pos + offset, this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static start(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Long id
 */
static addId(builder:flatbuffers.Builder, id:flatbuffers.Long) {
  builder.addFieldInt64(0, id, builder.createLong(0, 0));
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nameOffset
 */
static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset positionOffset
 */
static addPosition(builder:flatbuffers.Builder, positionOffset:flatbuffers.Offset) {
  builder.addFieldStruct(2, positionOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static end(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  builder.requiredField(offset, 6); // name
  return offset;
};

static create(builder:flatbuffers.Builder, id:flatbuffers.Long, nameOffset:flatbuffers.Offset, positionOffset:flatbuffers.Offset):flatbuffers.Offset {
  NodeVisualization.start(builder);
  NodeVisualization.addId(builder, id);
  NodeVisualization.addName(builder, nameOffset);
  NodeVisualization.addPosition(builder, positionOffset);
  return NodeVisualization.end(builder);
}
}
}
/**
 * @constructor
 */
export namespace executionGraph.serialization{
export class LinkVisualization {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns LinkVisualization
 */
__init(i:number, bb:flatbuffers.ByteBuffer):LinkVisualization {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param LinkVisualization= obj
 * @returns LinkVisualization
 */
static getRoot(bb:flatbuffers.ByteBuffer, obj?:LinkVisualization):LinkVisualization {
  return (obj || new LinkVisualization).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param executionGraph.serialization.SocketLinkDescription= obj
 * @returns executionGraph.serialization.SocketLinkDescription|null
 */
socket(obj?:NS11220090238097262337.executionGraph.serialization.SocketLinkDescription):NS11220090238097262337.executionGraph.serialization.SocketLinkDescription|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new NS11220090238097262337.executionGraph.serialization.SocketLinkDescription).__init(this.bb_pos + offset, this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static start(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nameOffset
 */
static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset socketOffset
 */
static addSocket(builder:flatbuffers.Builder, socketOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, socketOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static end(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  builder.requiredField(offset, 6); // socket
  return offset;
};

static create(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, socketOffset:flatbuffers.Offset):flatbuffers.Offset {
  LinkVisualization.start(builder);
  LinkVisualization.addName(builder, nameOffset);
  LinkVisualization.addSocket(builder, socketOffset);
  return LinkVisualization.end(builder);
}
}
}
/**
 * @constructor
 */
export namespace executionGraph.serialization{
export class GraphVisualization {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns GraphVisualization
 */
__init(i:number, bb:flatbuffers.ByteBuffer):GraphVisualization {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param GraphVisualization= obj
 * @returns GraphVisualization
 */
static getRoot(bb:flatbuffers.ByteBuffer, obj?:GraphVisualization):GraphVisualization {
  return (obj || new GraphVisualization).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param executionGraph.serialization.WorkspaceVisualization= obj
 * @returns executionGraph.serialization.WorkspaceVisualization|null
 */
workspaceVisualization(obj?:executionGraph.serialization.WorkspaceVisualization):executionGraph.serialization.WorkspaceVisualization|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new executionGraph.serialization.WorkspaceVisualization).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param number index
 * @param executionGraph.serialization.NodeVisualization= obj
 * @returns executionGraph.serialization.NodeVisualization
 */
nodeVisualization(index: number, obj?:executionGraph.serialization.NodeVisualization):executionGraph.serialization.NodeVisualization|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new executionGraph.serialization.NodeVisualization).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
};

/**
 * @returns number
 */
nodeVisualizationLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param number index
 * @param executionGraph.serialization.LinkVisualization= obj
 * @returns executionGraph.serialization.LinkVisualization
 */
linkVisualization(index: number, obj?:executionGraph.serialization.LinkVisualization):executionGraph.serialization.LinkVisualization|null {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new executionGraph.serialization.LinkVisualization).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
};

/**
 * @returns number
 */
linkVisualizationLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static start(builder:flatbuffers.Builder) {
  builder.startObject(4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nameOffset
 */
static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset workspaceVisualizationOffset
 */
static addWorkspaceVisualization(builder:flatbuffers.Builder, workspaceVisualizationOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, workspaceVisualizationOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nodeVisualizationOffset
 */
static addNodeVisualization(builder:flatbuffers.Builder, nodeVisualizationOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, nodeVisualizationOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createNodeVisualizationVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startNodeVisualizationVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset linkVisualizationOffset
 */
static addLinkVisualization(builder:flatbuffers.Builder, linkVisualizationOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, linkVisualizationOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createLinkVisualizationVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startLinkVisualizationVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static end(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // name
  return offset;
};

static create(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, workspaceVisualizationOffset:flatbuffers.Offset, nodeVisualizationOffset:flatbuffers.Offset, linkVisualizationOffset:flatbuffers.Offset):flatbuffers.Offset {
  GraphVisualization.start(builder);
  GraphVisualization.addName(builder, nameOffset);
  GraphVisualization.addWorkspaceVisualization(builder, workspaceVisualizationOffset);
  GraphVisualization.addNodeVisualization(builder, nodeVisualizationOffset);
  GraphVisualization.addLinkVisualization(builder, linkVisualizationOffset);
  return GraphVisualization.end(builder);
}
}
}
