
@startuml
set namespaceSeparator ::
skinparam shadowing false

class CefMessageRouterBrowserSide
class Handler as "CefMessageRouterBrowserSide::Handler"

namespace cefapp{
    class App{
        + OnContextInitialized()
    }
    class AppHandler #D3D3D3{
        + OnAfterCreated()
        + OnBeforeCloses()
        - m_router
        - m_messageDispatcher
        - initializeBackends()
    }

    class MessageDispatcher {
        + AddHandler(backendHandler)
        + RemoveHandler(backendHandler)
        - m_handlers
        - m_handlerMap
    }
    class ClientSchemeHandlerFactory
}


cefapp::App ..> cefapp::AppHandler : creates
cefapp::App --> cefapp::ClientSchemeHandlerFactory : registers

cefapp::AppHandler "1" o-left- CefMessageRouterBrowserSide
cefapp::AppHandler "1" *-- cefapp::MessageDispatcher
cefapp::MessageDispatcher -left-|> Handler
cefapp::MessageDispatcher "1..*" *--- backend::BackendMessageHandler

namespace backend {
    class Backend #D3D3D3
    class BackendMessageHandler #D3D3D3{
        + OnQuery(...) {abstract} 
    }

    class BackendFactory {
        + BackendData Create() {static}
    }

    class CreatorExecutionGraphBackend

    class DummyBackendMsgHandler
}

namespace executionGraph {
    class StaticFactory<T...>
}

cefapp::AppHandler ..> backend::BackendFactory : uses

backend::ExecutionGraphBackend --|> backend::Backend
backend::DummyBackendMsgHandler --|> backend::BackendMessageHandler

backend::BackendFactory ..> backend::CreatorExecutionGraphBackend : uses

backend::CreatorExecutionGraphBackend ..> backend::ExecutionGraphBackend : instanciates
backend::CreatorExecutionGraphBackend ..> backend::DummyBackendMsgHandler : instanciates

backend::DummyBackendMsgHandler "1" *-- backend::ExecutionGraphBackend

backend::BackendFactory .right.> executionGraph::StaticFactory

@enduml