#!/bin/bash

echo "Pre-Commit Hook:"
echo "clang-formatAll ..."
./tools/clang-formatAll.sh
echo "ts-formatAll ..."
./tools/ts-formatAll.sh
# echo "json-formatAll ..."
# ./tools/json-formatAll.sh
echo "Pre-Commit Hook [done]"

