// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var executionGraph = executionGraph || {};

/**
 * @const
 * @namespace
 */
executionGraph.serialization = executionGraph.serialization || {};

/**
 * @const
 * @namespace
 */
var executionGraphGui = executionGraphGui || {};

/**
 * @const
 * @namespace
 */
executionGraphGui.serialization = executionGraphGui.serialization || {};

/**
 * @constructor
 */
executionGraphGui.serialization.GetAllGraphTypeDescriptionsResponse = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {executionGraphGui.serialization.GetAllGraphTypeDescriptionsResponse}
 */
executionGraphGui.serialization.GetAllGraphTypeDescriptionsResponse.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {executionGraphGui.serialization.GetAllGraphTypeDescriptionsResponse=} obj
 * @returns {executionGraphGui.serialization.GetAllGraphTypeDescriptionsResponse}
 */
executionGraphGui.serialization.GetAllGraphTypeDescriptionsResponse.getRootAsGetAllGraphTypeDescriptionsResponse = function(bb, obj) {
  return (obj || new executionGraphGui.serialization.GetAllGraphTypeDescriptionsResponse).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {executionGraph.serialization.GraphTypeDescription=} obj
 * @returns {executionGraph.serialization.GraphTypeDescription}
 */
executionGraphGui.serialization.GetAllGraphTypeDescriptionsResponse.prototype.graphsTypes = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new executionGraph.serialization.GraphTypeDescription).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
executionGraphGui.serialization.GetAllGraphTypeDescriptionsResponse.prototype.graphsTypesLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
executionGraphGui.serialization.GetAllGraphTypeDescriptionsResponse.start = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} graphsTypesOffset
 */
executionGraphGui.serialization.GetAllGraphTypeDescriptionsResponse.addGraphsTypes = function(builder, graphsTypesOffset) {
  builder.addFieldOffset(0, graphsTypesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
executionGraphGui.serialization.GetAllGraphTypeDescriptionsResponse.createGraphsTypesVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
executionGraphGui.serialization.GetAllGraphTypeDescriptionsResponse.startGraphsTypesVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
executionGraphGui.serialization.GetAllGraphTypeDescriptionsResponse.end = function(builder) {
  var offset = builder.endObject();
  return offset;
};

// Exports for Node.js and RequireJS
this.executionGraph = executionGraph;
this.executionGraphGui = executionGraphGui;
